name: Generate SDK

on:
  workflow_dispatch:
    inputs:
      pub_ver_suffix:
        description: "Publish Version Suffix"
        required: false
      build_prefix:
        description: "Build Identifier Prefix"
        required: true
        default: "ghactions_"

env:
  PUBLISH_VERSION_SUFFIX: ${{ github.event.inputs.pub_ver_suffix }}
  BUILD_PREFIX: ${{ github.event.inputs.build_prefix }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Generate SDK
        run: npm run generate:sdk

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
              echo "changes=true" >> "$GITHUB_OUTPUT"; 
          fi

      - name: Validate SDK Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          npm install
          npm run build:sdk

      - name: Commit and push SDK changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Auto-generated SDK build"
          git push origin HEAD
